name: Question 3 binary provision

on:
  push:
  workflow_dispatch:

jobs:
  binary-provision:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Check if binaries exist
        id: check_binaries
        run: |
          USERNAME="${{ github.actor }}"
          if [ -f "q3/a/target_${USERNAME}" ] && [ -f "q3/b/target_${USERNAME}" ]; then
            echo "Binaries already exist for ${USERNAME}"
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Install dependencies
        if: steps.check_binaries.outputs.skip != 'true'
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y gcc-riscv64-linux-gnu python3-pip
          pip3 install numpy

      - name: Generate binaries
        env:
            GH_TOKEN: ${{ secrets.TEST_PAT }}
        if: steps.check_binaries.outputs.skip != 'true'
        run: |
          set -euo pipefail
          USERNAME="${{ github.actor }}"
          gh release download --repo s26-cso/a2-grader --pattern 'binary-provider.zip'
          unzip binary-provider.zip
          for SUBDIR in "a" "b"; do
            TARGET_PATH="q3/${SUBDIR}/target_${USERNAME}"
            if [ -f "${TARGET_PATH}" ]; then
              echo "${TARGET_PATH} already exists; skipping."
              continue
            fi
            python3 binary-provider/${SUBDIR}.py "${USERNAME}" "${TARGET_PATH}"
            mkdir -p "q3/${SUBDIR}"
            chmod +x "${TARGET_PATH}"
            git add "${TARGET_PATH}"
          done
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "Add q3 binaries for ${USERNAME}"
          git push
